### ISSUE TITLE
Reorganise - sensibly.

### ISSUE THREAD

**Issue by ikeycode** [serpent-os/recipes#1]
The component based organisation is a PITA, fix it.

**Comment by ermo** [comment]
GH can only list up to a certain amount of recipes in a single page before eliding.

Therefore, I propose that, if we reach a point where elision happens, we rejigger the groups such that we move the largest group of packages sharing the same prefix (e.g. python-*) from p/ to a separate py/ directory.

This strategy has worked well in e.g. Solus-land, so might work well here too?

**Comment by ikeycode** [comment]
I agree - and the `lib*` will also be a pain.
