### ISSUE TITLE
Replace `sudo` with `sudo-rs`

### ISSUE THREAD

**Issue by ikeycode** [serpent-os/recipes#151]
Outside of Serpent it's possible the current `sudo-rs` doesn't serve every need, but within it it'll certainly do the job for us.
For now we can either stub the `sudo` package *or* simply provide `sudo-rs` *as* `sudo` until such point as replaces support is in.

**Comment by ermo** [comment]
sudo-rs is usable since https://github.com/serpent-os/recipes/commit/1c3d61c335d8cbca7c84cce34236a91a7a50ed20
