### ISSUE TITLE
Please replace fbdev with SimpleDRM

### ISSUE THREAD

**Issue by Conan-Kudo** [serpent-os/recipes#155]
Please [replace fbdev with SimpleDRM](https://fedoraproject.org/wiki/Changes/ReplaceFbdevDrivers) in the SerpentOS kernel.

It's [recommended by KDE](https://community.kde.org/Distributions/Packaging_Recommendations#Kernel_configuration) and GNOME requires this too.

By having SimpleDRM in place, Wayland environments will work in cases where you don't have a DRM driver (e.g. when blocking nouveau and nvidia driver failed to build or similar). Replacing the fbdev interface with emulation by DRM also means that everything that uses framebuffer API will transparently switch to DRM and work fine.

This was a pre-requisite for Fedora KDE dropping X11 for KDE Plasma 6 in Fedora 40:

> #### [🔗](https://fedoraproject.org/wiki/Changes/KDE_Plasma_6#Why_drop_the_X11_session?) Why drop the X11 session?
> 
> Three reasons for this removal:
> 
> - [The Xorg server is deprecated since RHEL 9.0](https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/9/html/9.0_release_notes/deprecated_functionality#JIRA-RHELPLAN-121048) and will be dropped in "a future major RHEL release".
> - Graphics fallback modes are Wayland-friendly now with [SimpleDRM enabled since Fedora Linux 36](https://fedoraproject.org/wiki/Changes/ReplaceFbdevDrivers).
> - NVIDIA drivers (since v495~v515) support GBM for Wayland instead of EGLStreams. Wayland is fully supported on current NVIDIA drivers.
> 
> This will drastically reduce our support burden and give us the ability to focus on quality for the KDE Plasma stack and continue our feature-forward nature. The Fedora KDE SIG will maintain a single code stream for all supported distribution targets (Fedora Linux 40+, Fedora Extra Packages for Enterprise Linux 10+).
> 
> This also does not mean that X11 applications will not work in Plasma 6, as we will still support Xwayland for running X11 applications on Plasma Wayland.

And of course, the "future major RHEL release" is RHEL 10: https://www.redhat.com/en/blog/rhel-10-plans-wayland-and-xorg-server

**Comment by ikeycode** [comment]
Sorry got issue numbers wrong in my commits:

https://github.com/serpent-os/recipes/commit/881e65a8a2ee5cad6107f050d4f18389c7a38a58
https://github.com/serpent-os/recipes/commit/198e9e4680109d2bab9ffb88caffe60990041f4e

**Comment by ermo** [comment]
> Hi, guys; has this been done?

Yes. The issue was closed 18 months ago.
