### ISSUE TITLE
systemd: Please enable ukify, repoart and homed

### ISSUE THREAD

**Issue by hunger** [serpent-os/recipes#18]
I have been trying to add support for serpentos into mkosi (https://github.com/systemd/mkosi/pull/2238).

To be to use mkosi *inside* a serpentOS environemnt to build images, the `systemd-ukify` and `systemd-repart tools` are going to be needed. It would be super cool to have those once you get around to update systemd (ukify is not even in part of the version currently shipped).

To build a fully immutable system (with mkosi or not), `systemd-homed` would be wonderful to have.

**Comment by ikeycode** [comment]
`repart` and `homed` enabled in a566b283e50ebf04a92e4527cb411f39151efb8f
We use systemd-stable as our package, and I don't see `systemd-ukify` in it, is this in the main systemd repo ?

**Comment by joebonrichie** [comment]
Hmm deprecated
https://github.com/systemd/systemd/blob/v255/meson_options.txt#L508

**Comment by joebonrichie** [comment]
https://github.com/systemd/systemd/blame/v255/meson_options.txt#L508

**Comment by ikeycode** [comment]
Iirc the mkosi work stalled and the ukify thing is no longer essential for us. Feel free to reopen if needed !

**Comment by hunger** [comment]
Yes, the mkosi work has stopped, but it would IMHO still be nice to have the tool in place so that people can experiment with it.

But definitly not a showstopper or anything and I am fine with this being closed.
