### ISSUE TITLE
linux: Naming of kernel and initrd are inconsistent with the other kernel files

### ISSUE THREAD

**Issue by hunger** [serpent-os/recipes#19]
In `/usr/lib/kernel/` I end up with a list of files all related to some kernel `com.serpentos.(kvm|desktop).<VERSION>` with its matching initrd called `initrd-com.serpentos.(kvm|desktop).<VERSION>.

My OCD is triggered by the other files related to said kernel, which are called e.g. `config-<VERSION>.(kvm|desktop)`.

It would be so convenient if all files related to some kernel had the same suffix as the kernel itself.

Or maybe you could just put all the files without any suffix into `/usr/lib/modules/<VERSION>/` so that all the files are with the matching modules?

**Comment by ikeycode** [comment]
This is a layover from the `clr-boot-manager` days, we want to do something better when we integrate boot management with moss =)

**Comment by ermo** [comment]
The blsforme naming specification lives [here](https://github.com/serpent-os/blsforme?tab=readme-ov-file#filesystem-layout).

Closing as completed.
