### ISSUE TITLE
Relicense as MPL-2.0

### ISSUE THREAD

**Issue by ikeycode** [serpent-os/recipes#2]
Need confirmation from all existing contributors they're OK with relicensing from ZLIB to MPL-2.0 for the recipes.

- [x] @der-eismann 
- [x] @ermo 
- [x] @ReillyBrogan 
- [x] @joebonrichie 
- [x] @sunnyflunk
- [x] @livingsilver94 
- [x] @davidjharder
- [x] @GZGavinZhao
- [x] @GVitali1412 
- [x] @ikeycode

**Comment by ikeycode** [comment]
I, Ikey Doherty, confirm that I own the contributions in this repository under the terms of the Zlib license, and consent for them to be relicensed under the terms of the MPL-2.0 license. I understand these contributions will be accredited to the "Serpent OS Developers" collective to further protect the Serpent OS project and derivatives from fisically-motivated relicensing, patent trolls, etc.

**Comment by ermo** [comment]
I, Rune Morling, confirm that I own the contributions in this repository under the terms of the Zlib license, and consent for them to be relicensed under the terms of the MPL-2.0 license.

I understand that these contributions will be accredited to the "Serpent OS Developers" collective to further protect the Serpent OS project and derivatives from fiscally-motivated relicensing, patent trolls, etc.

**Comment by GZGavinZhao** [comment]
I, Gavin Zhao, confirm that I own the contributions in this repository under the terms of the Zlib license, and consent for them to be relicensed under the terms of the MPL-2.0 license.

I understand these contributions will be accredited to the "Serpent OS Developers" collective to further protect the Serpent OS project and derivatives from fisically-motivated relicensing, patent trolls, etc.

**Comment by der-eismann** [comment]
I, Philipp Trulson, confirm that I own the contributions in this repository under the terms of the Zlib license, and consent for them to be relicensed under the terms of the MPL-2.0 license.

I understand these contributions will be accredited to the "Serpent OS Developers" collective to further protect the Serpent OS project and derivatives from fisically-motivated relicensing, patent trolls, etc.

**Comment by davidjharder** [comment]
I, David Harder, confirm that I own the contributions in this repository under the terms of the Zlib license, and consent for them to be relicensed under the terms of the MPL-2.0 license.

I understand these contributions will be accredited to the "Serpent OS Developers" collective to further protect the Serpent OS project and derivatives from fiscally-motivated relicensing, patent trolls, etc.

**Comment by joebonrichie** [comment]
I, Joseph Riches, confirm that I own the contributions in this repository under the terms of the Zlib license, and consent for them to be relicensed under the terms of the MPL-2.0 license.

I understand these contributions will be accredited to the "Serpent OS Developers" collective to further protect the Serpent OS project and derivatives from fiscally-motivated relicensing, patent trolls, etc.

**Comment by GVitali1412** [comment]
I, Giacomo Vitali, confirm that I own the contributions in this repository under the terms of the Zlib license, and consent for them to be relicensed under the terms of the MPL-2.0 license.

I understand these contributions will be accredited to the "Serpent OS Developers" collective to further protect the Serpent OS project and derivatives from fisically-motivated relicensing, patent trolls, etc.

**Comment by livingsilver94** [comment]
I, Fabio Forni, confirm that I own the contributions in this repository under the terms of the Zlib license, and consent for them to be relicensed under the terms of the MPL-2.0 license.

I understand these contributions will be accredited to the "Serpent OS Developers" collective to further protect the Serpent OS project and derivatives from fisically-motivated relicensing, patent trolls, etc.

**Comment by ReillyBrogan** [comment]
I, Reilly Brogan, confirm that I own the contributions in this repository under the terms of the Zlib license, and consent for them to be relicensed under the terms of the MPL-2.0 license.

I understand these contributions will be accredited to the "Serpent OS Developers" collective to further protect the Serpent OS project and derivatives from fisically-motivated relicensing, patent trolls, etc.

**Comment by ikeycode** [comment]
@sunnyflunk im gonna need a reply on this fairly soon :)

**Comment by sunnyflunk** [comment]
All contributions made to this repository to which I hold the copyright, including all the works that are now attributed in the git history as the work of others, may be licensed and used under the terms of the MPL-2.0. Further to this, these contributions can be accredited to "Serpent OS Developers".

**Comment by ikeycode** [comment]
Thanks all!!
