### ISSUE TITLE
ncurses build is fucky-wucky

### ISSUE THREAD

**Issue by joebonrichie** [serpent-os/recipes#227]
serpent lib
$ file /home/ninya/sos/recipes/n/ncurses/ncurses-6.4-9.x86_64/usr/lib/libncursesw.so.6.4
/home/ninya/sos/recipes/n/ncurses/ncurses-6.4-9.x86_64/usr/lib/libncursesw.so.6.4: Compiled terminfo entry "vt510"

solus lib
$ file /usr/lib/libncursesw.so.6.5 
/usr/lib/libncursesw.so.6.5: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, BuildID[sha1]=f2c0c8d60dc11a6128b841dcae6760bc43b47f58, stripped

objdump and readelf can't read the serpent libncursesw.so.6.4 lib

screen FTBFS configure: error: !!! no tgetent - no screen (tgentent is provided by ncursesw lib)

**Comment by ikeycode** [comment]
False alarm. While `moss extract` is definitely busted, using `par_iter()` and seeking the content file, the true build failure is as follows:

```
configure:4942: checking select with  -lnet -lnsl...
configure:4955: clang -o conftest -D_FORTIFY_SOURCE=2 -O2 -fno-omit-frame-pointer -mno-omit-leaf-frame-pointer -fstack-protector --param ssp-buffer-size=32 -g -fasynchronous-unwind-tables -march=x86-64-v2 -mtune=ivybridge -mprefer-vector-width=128 -pipe -Wformat -Wformat-security -Wno-error -fPIC  -Wl,--as-needed -Wl,--icf=safe -Wl,-Bsymbolic-functions -Wl,-O2,--gc-sections -Wl,-z,pack-relative-relocs -Wl,-z,relro,-z,now conftest.c  -lnet -lnsl >&5
conftest.c:45:1: error: call to undeclared function 'select'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
   45 | select(0, 0, 0, 0, 0);
      | ^
1 error generated.
configure:4955: $? = 1
configure: failed program was:
| /* confdefs.h */
```

Note the introduction of the default error for `implicit-function-declaration` in clang16+: https://www.redhat.com/en/blog/new-warnings-and-errors-clang-16

Even with it fixed, the build hangs, but with `toolchain: gnu` it works
