### ISSUE TITLE
[FTBFS] linux-desktop: 6.11.0

### ISSUE THREAD

**Issue by ikeycode** [serpent-os/recipes#386]
Will revise this issue later with logs when I get access, as this is mostly an issue for myself.

In early build of 6.11.0 we're seeing a crash in clang/llvm during IR emission.

**Comment by ermo** [comment]
Fixed since https://github.com/serpent-os/recipes/commit/3756a41377c229ef0449e3552484fe98858cc158 (chiefly due to fixes landed in https://github.com/serpent-os/recipes/commit/7d8ddc12675683f3523a34a4925bd979483624b9)
