### ISSUE TITLE
[Package Update]: Linux-headers

### ISSUE THREAD

**Issue by ryzendew** [serpent-os/recipes#427]
### Existing package update request?

- [X] I have searched open package request reports for an equivalent package update request

### Name

linux-headers

### Version

6.12.1-58

### Link to the release notes or announcement.

N/A

### Reason for update

i am working on getting the nvidia drivers to work in This OS and linux headers are needed

**Comment by ermo** [comment]
The headers used for this are `linux-current-devel`.

Additionally, @ikeycode is going to handle this. The NVIDIA enablement plan is here: https://github.com/serpent-os/recipes/issues/435
