### ISSUE TITLE
phoronix-test-suite versioning

### ISSUE THREAD

**Issue by FabioLolix** [serpent-os/recipes#431]
Hi, I got the notifications from repology.org that a new PTS versions have been packaged but looking at upstream this version have not been tagged and looking at the [stone.yaml](https://github.com/serpent-os/recipes/commit/98cf0e21221da62d1eb89f7b57d56582a4862caa#diff-9e8cbf4baf34aa47756d20a47d8e4360df3e392bc3df8c79cdb02b36371b7803) doen't even clone https://github.com/phoronix-test-suite/phoronix-test-suite/commit/c2605245acf203370e67a41f898ad22863c4c467 but the latest commit https://github.com/phoronix-test-suite/phoronix-test-suite/commit/f665ba8ee724331f5bc375715089ad6393bcf10e

https://repology.org/project/phoronix-test-suite/versions

Would be nice to properly calculate the version instead of faking it, you could do like in Arch Linux pkgbuilds plus repology have a rule to exclude stuff after the `+`, see for example `caribou` package which have version `0.4.21+75+g8ad9883`

* https://gitlab.archlinux.org/archlinux/packaging/packages/caribou/-/blob/main/PKGBUILD?ref_type=heads
* https://repology.org/project/caribou/versions

**Comment by ikeycode** [comment]
Not sure if you're helping or scolding, unclear. PTS has stopped issuing tags but clearly updates the versions:

https://github.com/phoronix-test-suite/phoronix-test-suite/commit/c2605245acf203370e67a41f898ad22863c4c467

So, it's 10.8.5 according to PTS's own version, and using latest git because php8 support, and because upstream clearly stopped issuing tags or having a proper software release cycle since ~2022?

**Comment by ikeycode** [comment]
Sidenote if you're looking at contributing to a versioning policy for packages, quite happy to discuss that in a separate issue with team input so the necessary tooling changes can be made for verification purposes.

**Comment by FabioLolix** [comment]
> PTS has stopped issuing tags but clearly updates the versions:
> 
> https://github.com/phoronix-test-suite/phoronix-test-suite/commit/c2605245acf203370e67a41f898ad22863c4c467
>
> So, it's 10.8.5 according to PTS's own version

Have seen that but there is also `[GIT]` there which IMO mean it is in progress/incomplete, I have come here first since it is not buid that commit but latest

> using latest git because php8 support, and because upstream clearly stopped issuing tags or having a proper software release cycle since ~2022?

I have nothing against using latest commits in packages but this lack correlation between the downloaded version and package version and inconvenience all the other packages tracked at repology. Could be something like `10.8.4+77+gf665ba8`

> Sidenote if you're looking at contributing to a versioning policy for packages

I'm not sure I'm fluent or informed enough for that but where would happen?

btw there is a thing like `epoch=` for passing a downgrade as update on SerpentOS?

**Comment by ikeycode** [comment]
We don't need to do downgrades that way, we bump the release number as the primary control for "this is a new build", moss handles the difference based on the layered repo indices. @ermo and myself have been discussing and will have an issue up soon to determine the version scheme (but it'll quite likely be `+git.$ref` (allowing for svn/hg/etc)
