### ISSUE TITLE
steam bug: glXChooseVisual failed

### ISSUE THREAD

**Issue by flukejones** [serpent-os/recipes#442]
Steam currently fails with this:
```
steamwebhelper.sh[20128]: Starting steamwebhelper with Sniper steam runtime at /home/luke/.local/share/Steam/ubuntu12_64/steam-runtime-sniper/_v2-entry-point
src/vgui2/src/surface_linux.cpp (1954) : glXChooseVisual failed
src/vgui2/src/surface_linux.cpp (1954) : glXChooseVisual failed
src/vgui2/src/surface_linux.cpp (1954) : Fatal assert; application exiting
src/vgui2/src/surface_linux.cpp (1954) : Fatal assert; application exiting
12/16 22:14:23 Init: Installing breakpad exception handler for appid(steam)/version(1733265492)/tid(20084)
```

# System Details Report
---

## Report details
- **Date generated:**                              2024-12-16 22:17:39

## Hardware Information:
- **Hardware Model:**                              ASUSTeK COMPUTER INC. ROG Zephyrus G16 GA605WI_GA605WI
- **Memory:**                                      32.0 GiB
- **Processor:**                                   AMD Ryzen™ AI 9 HX 370 w/ Radeon™ 890M × 24
- **Graphics:**                                    NV196
- **Graphics 1:**                                  AMD Radeon™ Graphics
- **Disk Capacity:**                               2.0 TB

## Software Information:
- **Firmware Version:**                            GA605WI.306
- **OS Name:**                                     Serpent OS 0.24.5 (fstx #44)
- **OS Build:**                                    (null)
- **OS Type:**                                     64-bit
- **GNOME Version:**                               47
- **Windowing System:**                            Wayland
- **Kernel Version:**                              Linux 6.12.5-76.desktop

Unsure what else to provide at this point. Nvidia drivers not installed, using nouveau. vkcube and glxgears both use nouveau fine.

Tried on both the AMD iGPU and NV dGPU.

**Comment by flukejones** [comment]
Searching the error turns up a lot of generally useful info. Seems to be a common occurrence over the last 5+ years.

**Comment by flukejones** [comment]
Also seems required is:
```diff
…/s/steam on  main [$!] took 5s 
❯ git diff
diff --git a/s/steam/manifest.x86_64.bin b/s/steam/manifest.x86_64.bin
index ea493db3150b..0bfe8e6fcda6 100644
Binary files a/s/steam/manifest.x86_64.bin and b/s/steam/manifest.x86_64.bin differ
diff --git a/s/steam/manifest.x86_64.jsonc b/s/steam/manifest.x86_64.jsonc
index 115bf5a99a90..332b04d0e91d 100644
--- a/s/steam/manifest.x86_64.jsonc
+++ b/s/steam/manifest.x86_64.jsonc
@@ -5,6 +5,7 @@
                "steam": {
                        "depends": [
                                "binary(cmp)",
+                               "binary(lspci)",
                                "binary(tar)",
                                "binary(zenity)",
                                "soname(libGL.so.1(386))",
diff --git a/s/steam/stone.yaml b/s/steam/stone.yaml
index c6eab7e0ad45..2e19aabd4c3e 100644
--- a/s/steam/stone.yaml
+++ b/s/steam/stone.yaml
@@ -15,6 +15,7 @@ description : |
 license     : Distributable
 rundeps     :
     - binary(cmp)
+    - binary(lspci)
     - binary(tar)
     - binary(zenity)
     - soname(libdrm.so.2(386))
```

**Comment by ikeycode** [comment]
i believe this to be fixed =)

**Comment by flukejones** [comment]
No need to believe when it is fact :rocket:
