### ISSUE TITLE
Get all packages up to date and secure

### ISSUE THREAD

**Issue by ermo** [serpent-os/recipes#9]
We have a pressing need to get production ready docker base images for infrastructure, as well as shift into alpha ISOs stage.

To do that, we need the base cleaned up and updated, while we bring moss-rs up and boulder-rs into existence.

For now it's sufficient to use legacy moss/boulder until such time as we announce the shift and get the infrastructure over to the Rust versions. This will be very soon for moss-rs.

Use this as a tracker issue for the necessary package updates in the volatile repo.

Originally reported by @ikeycode

**Comment by ikeycode** [comment]
The infra and client systems are all using the rust implementations now.

Many packages have already been uplifted this is just daily maintenance now :)
